[project]
name = "crimosonguard"
version = "0.1.0"
description = "Gioco in 2d in cui sarete un samurai a difesa di un tempio: correte, lanciate coltelli e abbattete orde di mostri una dopo l'altra prima che arrivino a distruggere il tempio al centro della mappa. By L. Paoletti e S. Amadio"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pygame>=2.6.1",
    "platformdirs>=3.0.0",
]

[project.scripts]
crimsonguard = "crimsonguard:main"

[tool.hatch.build.targets.wheel]
packages = ["src/crimsonguard"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"